# Source de données
library(shiny)
library(plotly)
library(dplyr)
library(here)
library(ggplot2)
library(gganimate)
library(purrr)
library(tidyr)
library(janitor)
library(readr)
library(stringr)
library(lazyeval)
source(here("R/ETL.R"), local = TRUE)
df_map <- etl(here("data", "global_power_plant_database.csv"), c('capacity_mw', 'latitude', 'longitude', 'primary_fuel'))
df_time <- etl(here("data", "global_power_plant_database.csv"), c('capacity_mw', 'commissioning_year', 'country_long', 'primary_fuel'))
